In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../')
sys.path.append('../utils/')
from utils import common_utils
from utils import data_prepare_utils
import seaborn as sns
from glob import glob

In [2]:
okaribe_train_path = '/data/renjie/tunnel_cv/okaribe_bk/data/train/masterdataset/'
okaribe_test_path = '/data/renjie/tunnel_cv/okaribe_bk/data/test/masterdataset/'
train_paths = glob(okaribe_train_path+'*.csv')
test_paths = glob(okaribe_test_path+'*.csv')
paths = train_paths+test_paths
paths

['/data/renjie/tunnel_cv/okaribe_bk/data/train/masterdataset/2019_03__master_dataset.csv',
 '/data/renjie/tunnel_cv/okaribe_bk/data/train/masterdataset/2019_01__master_dataset.csv',
 '/data/renjie/tunnel_cv/okaribe_bk/data/train/masterdataset/2019_02__master_dataset.csv',
 '/data/renjie/tunnel_cv/okaribe_bk/data/train/masterdataset/2019_04__master_dataset.csv',
 '/data/renjie/tunnel_cv/okaribe_bk/data/test/masterdataset/2019_05__master_dataset.csv',
 '/data/renjie/tunnel_cv/okaribe_bk/data/test/masterdataset/2019_06__master_dataset.csv']

In [3]:
dfs = []
for p in paths:
    dfs.append(pd.read_csv(p))

In [4]:
okaribe_df = pd.concat(dfs)
okaribe_df['datetime'] = pd.DatetimeIndex(okaribe_df['datetime'])
okaribe_df['path'] = okaribe_df['name']

okaribe_df = okaribe_df.sort_values(['datetime'])
okaribe_df = okaribe_df.drop(columns = ['name'])

In [5]:
okaribe_df

,datetime,cycle,Wait,Exc_MC,Drl_DB,Muc,Prf,Sht,Blt,AGF,Prb,Oth,label,path
0,2019-01-01 00:00:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0000.jpg
1,2019-01-01 00:05:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0005.jpg
2,2019-01-01 00:10:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0010.jpg
3,2019-01-01 00:15:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0015.jpg
4,2019-01-01 00:20:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0020.jpg
5,2019-01-01 00:25:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0025.jpg
6,2019-01-01 00:30:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0030.jpg
7,2019-01-01 00:35:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0035.jpg
8,2019-01-01 00:40:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0040.jpg
9,2019-01-01 00:45:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0045.jpg
10,2019-01-01 00:50:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0050.jpg
11,2019-01-01 00:55:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0055.jpg
12,2019-01-01 01:00:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0100.jpg
13,2019-01-01 01:05:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0105.jpg
14,2019-01-01 01:10:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0110.jpg
15,2019-01-01 01:15:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0115.jpg
16,2019-01-01 01:20:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0120.jpg
17,2019-01-01 01:25:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0125.jpg
18,2019-01-01 01:30:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0130.jpg
19,2019-01-01 01:35:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0135.jpg
20,2019-01-01 01:40:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0140.jpg
21,2019-01-01 01:45:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0145.jpg
22,2019-01-01 01:50:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0150.jpg
23,2019-01-01 01:55:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0155.jpg
24,2019-01-01 02:00:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0200.jpg
25,2019-01-01 02:05:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0205.jpg
26,2019-01-01 02:10:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0210.jpg
27,2019-01-01 02:15:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0215.jpg
28,2019-01-01 02:20:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0220.jpg
29,2019-01-01 02:25:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0225.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8610,2019-06-30 21:30:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2130.jpg
8611,2019-06-30 21:35:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2135.jpg
8612,2019-06-30 21:40:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2140.jpg
8613,2019-06-30 21:45:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2145.jpg
8614,2019-06-30 21:50:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2150.jpg
8615,2019-06-30 21:55:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2155.jpg
8616,2019-06-30 22:00:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2200.jpg
8617,2019-06-30 22:05:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2205.jpg
8618,2019-06-30 22:10:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2210.jpg
8619,2019-06-30 22:15:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2215.jpg
8620,2019-06-30 22:20:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2220.jpg
8621,2019-06-30 22:25:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2225.jpg
8622,2019-06-30 22:30:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2230.jpg
8623,2019-06-30 22:35:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2235.jpg
8624,2019-06-30 22:40:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2240.jpg
8625,2019-06-30 22:45:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2245.jpg
8626,2019-06-30 22:50:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2250.jpg
8627,2019-06-30 22:55:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2255.jpg
8628,2019-06-30 23:00:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2300.jpg
8629,2019-06-30 23:05:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2305.jpg
8630,2019-06-30 23:10:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2310.jpg
8631,2019-06-30 23:15:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2315.jpg
8632,2019-06-30 23:20:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2320.jpg
8633,2019-06-30 23:25:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2325.jpg
8634,2019-06-30 23:30:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2330.jpg
8635,2019-06-30 23:35:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2335.jpg
8636,2019-06-30 23:40:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2340.jpg
8637,2019-06-30 23:45:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2345.jpg
8638,2019-06-30 23:50:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2350.jpg
8639,2019-06-30 23:55:00,NaN,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190630-2355.jpg

In [6]:
full_save_path = '../data/okaribe_full.csv'
okaribe_df.to_csv(full_save_path,index=False)

In [7]:
okaribe_train_df = okaribe_df[okaribe_df['datetime'] < '2019-04-01']
okaribe_test_df = okaribe_df[okaribe_df['datetime'] > '2019-04-01']

In [8]:
train_save_path = '../data/train_data/okaribe_train.csv'
test_save_path = '../data/test_data/okaribe_test.csv'

okaribe_train_df.to_csv(train_save_path,index=False)
okaribe_test_df.to_csv(test_save_path,index=False)

In [9]:
okaribe_train_df.iloc[:10]

,datetime,cycle,Wait,Exc_MC,Drl_DB,Muc,Prf,Sht,Blt,AGF,Prb,Oth,label,path
0,2019-01-01 00:00:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0000.jpg
1,2019-01-01 00:05:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0005.jpg
2,2019-01-01 00:10:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0010.jpg
3,2019-01-01 00:15:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0015.jpg
4,2019-01-01 00:20:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0020.jpg
5,2019-01-01 00:25:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0025.jpg
6,2019-01-01 00:30:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0030.jpg
7,2019-01-01 00:35:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0035.jpg
8,2019-01-01 00:40:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0040.jpg
9,2019-01-01 00:45:00,0.0,1,0,0,0,0,0,0,0,0,0,0,data/okaribe/data/C20190101-0045.jpg

In [10]:
import shutil

In [11]:
train_root = "/data/renjie/tunnel_cv/okaribe_bk/data/train/cctv/*"
test_root = "/data/renjie/tunnel_cv/okaribe_bk/data/test/cctv/*"

In [12]:
paths = glob(train_root)
paths+=glob(test_root)

In [13]:
# dst_path = "/data/renjie/tunnel_cv/okaribe/data/"
# for p in paths:
#     filenames = glob(p + '/*.jpg')
#     for f in filenames:
#         shutil.copy(f,dst_path )

In [14]:
def to_one_hot(val,num_classes):
    onehot = np.zeros(num_classes)
    onehot[val] = 1
    return onehot